### ISSUE TITLE
AWS JS SDK v3 support

### ISSUE THREAD

**Issue by paul-uz** [BlackbirdHQ/amazon-dax-client#9]
Lots of people are asking for a DAX solution when using the AWS JS SDK v3, but AWS are saying its not something they are going to do.

I assume this repo is for the package mentioned in the AWS docs for using DAX with the v2 SDK on Node?

If so, can you look at updating this package to support the v3 SDK?

**Comment by martinjlowm** [comment]
Hi Paul,

We are not maintaining this package - in fact, I had forgotten all about this fork. We used to use it as a patched version of the original repo, but nowadays we don't use DAX at all. I was hoping to hear some news about DAX at re:Invent last week about better support, it feels a bit awkward to use in my opinion.

**Comment by paul-uz** [comment]
Do you know where the original repo is? This one isn't showing as a fork (github usually shows the original repo link under the repo title, but im not seeing it in this case).

Looks like they might have binned off DAX without telling anyone :/

**Comment by martinjlowm** [comment]
Yeah... they don't have it hosted here. Think we just made it into a repo from the NPM package. You can see it from the commit history that we only have our own logged commits.

**Comment by paul-uz** [comment]
Ah ok. What a shame. Thanks anyway!!
